
export const LOADING = "LOADING"

export const COUNTER_INCREMENTER = "a/b"

export const READ_PRODUCTS = "READ_PRODUCTS"

export const WRITE_PRODUCTS = "WRITE_PRODUCTS"

export const WRITE_PRODUCT = "WRITE_PRODUCT"
export const WRITE_PRODUCT_FAILED = "WRITE_PRODUCT_FAILED"

export const WRITE_PRODUCTS_BY_TYPE = "WRITE_PRODUCT_BY_TYPE"


export const WRITE_CATEGORIES = "WRITE_CATEGORIES"
export const WRITE_CATEGORIES_FAILED = "WRITE_CATEGORIES_FAILED"


export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const UPDATE_PRODUCT_IMAGEVALUE = "UPDATE_PRODUCT_IMAGEVALUE"
 