export const COUNTER_INCREMENTER = "a/b"

export const READ_PRODUCTS = "READ_PRODUCTS"

export const WRITE_PRODUCTS = "WRITE_PRODUCTS"

export const WRITE_PRODUCT = "WRITE_PRODUCT"

export const UPDATE_PRODUCT = "UPDATE_PRODUCT"

export const UPDATE_PRODUCT_IMAGEVALUE = "UPDATE_PRODUCT_IMAGEVALUE"

export const WRITE_GENRES = "WRITE_GENRES"